services:
  wordpress:
    image: wordpress
    container_name: wordpress
    ports:
      - 80:80
    environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: my_username
        WORDPRESS_DB_PASSWORD: my_password
        WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql
    container_name: mysql
    environment:
        MYSQL_DATABASE: wordpress
        MYSQL_USER: my_username
        MYSQL_PASSWORD: my_password
        MYSQL_RANDOM_ROOT_PASSWORD: '1'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: my_username
      MYSQL_ROOT_PASSWORD: my_password
